openapi: 3.0.0
info:
  title: ECO-FMM-FASTAPI
  description: API for ECO Functional Memory Module
  version: 1.1
servers:
  - url: http://0.0.0.0/
paths:
  /tasks:
    get:
      summary: Retrieve all tasks
      responses:
        200:
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task or update an existing one based on its title
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        201:
          description: Task created or updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  task_id:
                    type: integer
                    description: ID of the created or updated task
                  message:
                    type: string
                    description: Success message
  /feedback:
    post:
      summary: Submit user feedback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserFeedback'
      responses:
        201:
          description: Feedback submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback_id:
                    type: integer
                    description: ID of the submitted feedback
                  message:
                    type: string
                    description: Success message
components:
  schemas:
    Task:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        dueDate:
          type: string
          format: date
        status:
          type: string
        priority:
          type: integer
          minimum: 1
          maximum: 5
          description: Task priority from 1 (highest) to 5 (lowest)
        dependencies:
          type: array
          items:
            type: string
    ChatHistory:
      type: object
      properties:
        summary:
          type: string
    UserFeedback:
      type: object
      properties:
        user_id:
          type: integer
        feedback:
          type: string
