openapi: 3.0.0
info:
  title: ECO-FMM-FASTAPI
  version: v2.0.0
  description: FastAPI application to manage tasks and receive feedback
  contact:
    name: C-BIAS ENTERPRISES
    year: 2024
servers:
  - url: https://eco-fmm.replit.app
    description: Main server
paths:
  /tasks:
    get:
      summary: Retrieve a list of tasks
      operationId: getTasks
      parameters:
        - in: query
          name: category
          schema:
            type: string
          required: false
          description: Filter tasks by status category
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
      security:
        - bearerAuth: []

    post:
      summary: Create or update a task
      operationId: manageTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Task created or updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  task_id:
                    type: integer
                  message:
                    type: string
      security:
        - bearerAuth: []

  /feedback:
    post:
      summary: Submit user feedback
      operationId: submitFeedback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserFeedback'
      responses:
        '201':
          description: Feedback received
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback_id:
                    type: integer
                  message:
                    type: string
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth: # Define the security scheme as HTTP Bearer
      type: http
      scheme: bearer
      bearerFormat: JWT # Specify the bearer format, if applicable (e.g., JWT)
  schemas:
    Task:
      type: object
      required:
        - title
        - description
        - due_date
        - status
        - priority
      properties:
        id:
          type: integer
          format: int64
          description: Unique ID of the task
        title:
          type: string
          description: Title of the task
        description:
          type: string
          description: Description of the task
        due_date:
          type: string
          format: date-time
          description: Due date of the task
        status:
          type: string
          description: Status of the task
        priority:
          type: integer
          description: Priority of the task, where 1 is the highest priority
          minimum: 1
          maximum: 5
        area:
          type: string
          description: The area of the task (e.g., personal, work)

    UserFeedback:
      type: object
      required:
        - user_id
        - feedback
      properties:
        user_id:
          type: integer
          format: int64
          description: Unique identifier of the user
        feedback:
          type: string
          description: Feedback provided by the user

security:
  - bearerAuth: []
