openapi: 3.0.0
info:
  title: ECO-FMM-FASTAPI
  version: v1.4.0  # Version number updated to match main.py
  description: FastAPI application to manage tasks and receive feedback
  contact:
    name: C-BIAS ENTERPRISES
    year: 2024
servers:
  - url: http://example.com/
    description: Main server
paths:
  /:
    get:
      summary: Root Endpoint
      operationId: readRoot
      responses:
        '200':
          description: Welcome Message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Welcome to the ECO-FMM-FASTAPI v1.4.0 API!"  # Updated example message to v1.4.0

  /tasks:
    get:
      summary: Get All Tasks
      operationId: getTasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

    post:
      summary: Create or Update a Task
      operationId: manageTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Task created or updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  task_id:
                    type: integer
                  message:
                    type: string
                  example:  # Added missing example field
                    task_id: 3
                    message: "Task updated successfully."

  /feedback:
    post:
      summary: Submit Feedback
      operationId: submitFeedback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserFeedback'
      responses:
        '201':
          description: Feedback submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback_id:
                    type: integer
                  message:
                    type: string  
                  example:  # Added missing example field
                    feedback_id: 1
                    message: "Feedback submitted successfully."

components:
  schemas:
    Task:
      type: object
      required:
        - title
        - description
        - due_date
        - status
      properties:
        id: 
          type: integer
          description: Unique ID of the task
        title:
          type: string
        description:
          type: string
        due_date:
          type: string
        status:
          type: string
        priority:
          type: integer
          description: Task priority from 1 (highest) to 5 (lowest)
          minimum: 1
          maximum: 5
        # Removed unnecessary dependencies field from Task schema

    UserFeedback:
      type: object
      required:
        - user_id
        - feedback
      properties:
        user_id:
          type: integer
        feedback:
          type: string
          