openapi: 3.0.0
info:
  title: ECO-FMM-FASTAPI
  version: v2.1.0
  description: FastAPI application to manage tasks and receive feedback
  contact:
    name: C-BIAS ENTERPRISES
    year: 2024
servers:
  - url: https://eco-fmm.replit.app
    description: Main server
paths:
  /download-logs:
    get:
      summary: Download logs
      description: Allows the client to download the 'database_actions.log' file for debugging purposes.
      responses:
        "200":
          description: A log file to download.
          content:
            text/plain:
              schema:
                type: string
                format: binary
        "500":
          description: An error occurred while trying to serve the log file.
  /tasks:
    post:
      summary: Create or update a task
      operationId: manageTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: Task created or updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  task_id:
                    type: integer
                    description: Unique ID of the task
                  message:
                    type: string
                    description: Response message
      security:
        - bearerAuth: []
    get:
      summary: Retrieve a list of tasks
      operationId: getTasks
      responses:
        "200":
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
      security:
        - bearerAuth: []
  /tasks/{task_id}:
    get:
      summary: Retrieve a task by ID
      operationId: getTaskById
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: integer
          description: Unique ID of the task
      responses:
        "200":
          description: Detailed information about a task
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: Task not found
      security:
        - bearerAuth: []
  /feedback:
    post:
      summary: Submit user feedback
      operationId: submitFeedback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserFeedback"
      responses:
        "201":
          description: Feedback received
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback_id:
                    type: integer
                    description: Unique ID of the feedback
                  message:
                    type: string
                    description: Response message
      security:
        - bearerAuth: []
  /logs:
    get:
      operationId: getLogContents
      summary: Get the contents of the log file
      description: Retrieve the error log contents from the generated log file.
      responses:
        "200":
          description: Log contents retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  log_contents:
                    type: string
                    description: The contents of the log file.
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Detailed error message.
  /behaviors:
    post:
      summary: Add a new behavior
      operationId: addBehavior
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Behavior"
      responses:
