openapi: 3.0.0
info:
  title: ECO-FMM-FASTAPI
  version: v2.2.0
  description: FastAPI application to manage tasks and receive feedback
  contact:
    name: C-BIAS ENTERPRISES
    email: contact@cbias-enterprises.com
servers:
  - url: https://eco-fmm.replit.app
    description: Main server
paths:
  /download-logs:
    get:
      operationId: downloadLogs
      summary: Download logs
      description: Allows the client to download the 'database_actions.log' file for debugging purposes.
      responses:
        "200":
          description: A log file to download.
          content:
            text/plain:
              schema:
                type: string
                format: binary
        "500":
          description: An error occurred while trying to serve the log file.
  /tasks:
    post:
      summary: Create or update a task
      operationId: manageTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: Task created or updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  task_id:
                    type: integer
                    description: Unique ID of the task
                  message:
                    type: string
                    description: Response message
      security:
        - bearerAuth: []
    get:
      summary: Retrieve a list of tasks
      operationId: getTasks
      responses:
        "200":
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
      security:
        - bearerAuth: []
  /tasks/{task_id}:
    get:
      summary: Retrieve a task by ID
      operationId: getTaskById
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: integer
          description: Unique ID of the task
      responses:
        "200":
          description: Detailed information about a task
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: Task not found
      security:
        - bearerAuth: []
  /feedback:
    post:
      summary: Submit user feedback
      operationId: submitFeedback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserFeedback"
      responses:
        "201":
          description: Feedback received
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback_id:
                    type: integer
                    description: Unique ID of the feedback
                  message:
                    type: string
                    description: Response message
      security:
        - bearerAuth: []
  /behaviors:
    post:
      summary: Add a new behavior
      operationId: addBehavior
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Behavior"
      responses:
        "201":
          description: Behavior added
          content:
            application/json:
              schema:
                type: object
                properties:
                  behavior_id:
                    type: integer
                    description: Unique ID of the behavior
                  message:
                    type: string
                    description: Response message
      security:
        - bearerAuth: []
  /generate-hashtags:
    post:
      summary: Generate hashtags
      operationId: generateHashtags
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: Text to generate hashtags from
      responses:
        "200":
          description: Generated hashtags
          content:
            application/json:
              schema:
                type: object
                properties:
                  hashtags:
                    type: array
                    items:
                      type: string
                    description: List of generated hashtags
        "400":
          description: Language detection failed
      security:
        - bearerAuth: []
  /backup-dbs:
    get:
      summary: Backup databases
      operationId: backupDbs
      responses:
        "200":
          description: A zip file containing the backups of the databases
          content:
            application/x-zip-compressed:
              schema:
                type: string
                format: binary
        "500":
          description: An error occurred while trying to backup the databases
      security:
        - bearerAuth: []
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          description: Unique ID of the task
        title:
          type: string
          description: Title of the task
        description:
          type: string
          description: Description of the task
        due_date:
          type: string
          description: Due date of the task in DD-MM-YYYY format
        status:
          type: string
          description: Status of the task
        priority:
          type: integer
          description: Priority of the task
        area:
          type: string
          description: Area of the task
        FULLCONTENT:
          type: string
          description: Complete content of the task
        hashtags:
          type: string
          description: Hashtags associated with the task
        related_tasks:
          type: array
          items:
            type: integer
          description: List of identifiers for related tasks
    UserFeedback:
      type: object
      properties:
        user_id:
          type: integer
          description: ID of the user providing feedback
        feedback:
          type: string
          description: Feedback content
    Behavior:
      type: object
      properties:
        id:
          type: integer
          description: Unique ID of the behavior
        description:
          type: string
          description: Description of the behavior
securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT